#! /bin/sh
# Update the local files from GNULIB.  Currently assumes that the current
# GNULIB sources are in a directory parallel with this one.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

# Where to find the GNULIB sources.
GNULIB=../gnulib
GNULIB_TOOL=$GNULIB/gnulib-tool

# Which modules to update.
MODULES="gettext vasnprintf regex atexit save-cwd dirname exit exitfail
	 extensions fnmatch-posix fnmatch mkstemp getopt stdbool getline
	 getnline getndelim2 gethostname strcase getpass-gnu gettimeofday
	 timespec gettime unlocked-io tzset restrict time_r mktime minmax
	 memmove"

# Are the GNULIB sources really where we expect them?
if test -r $GNULIB && test -d $GNULIB \
   && test -r $GNULIB_TOOL && test -f $GNULIB_TOOL; then :; else
  echo GNULIB sources not found. >&2
  exit 1
fi

# Prevent lib/Makefile.am from being overwritten.
mv lib/Makefile.am lib/Makefile.am.save

# Run the update.
$GNULIB_TOOL --import $MODULES >/dev/null

# Extract the files we imported.
$GNULIB_TOOL --extract-filelist $MODULES >gnulib.new

# Wartn the user if the filelist has changed.
if cmp gnulib.txt gnulib.new >/dev/null; then :; else
  echo '********************************************************************' >&2
  echo The file list has changed.  You may need to add or remove files from >&2
  echo CVS and/or EXTRA_DIST in m4/Makefile.am.  Use \`cvs diff gnulib.txt\'
>&2
  echo to view changes. >&2
  echo '********************************************************************' >&2
fi

# Save the file list for next time.
mv gnulib.new gnulib.txt

# Warn the user if changes have been made to the Makefile.am.
if cmp lib/Makefile.am lib/Makefile.gnulib >/dev/null; then :; else
  echo '********************************************************************' >&2
  echo Makefile.am needs updating. Use \`cvs diff lib/Makefile.gnulib\' >&2
  echo to view changes. >&2
  echo '********************************************************************' >&2
fi

# Save the generated lib/Makefile.am for next time.
mv lib/Makefile.am lib/Makefile.gnulib

# Restore lib/Makefile.am.
mv lib/Makefile.am.save lib/Makefile.am
